### ISSUE TITLE
remotese example : webservice example, web polling fails on jdk8.40+

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#222]
Reproduced on : 
- jdk1.8.0_231
- adoptopenjdk-11.jdk

a publish queue is not created : 
```
java.lang.IllegalStateException: Keyple Dto Queue is null, what to do?
	at org.eclipse.keyple.example.remote.transport.wspolling.server.EndpointPolling.sendDTO(EndpointPolling.java:118)
	at org.eclipse.keyple.example.remote.transport.wspolling.server.WsPServer.sendDTO(WsPServer.java:113)
	at org.eclipse.keyple.plugin.remotese.rm.AbstractRemoteMethodTx.send(AbstractRemoteMethodTx.java:99)
	at org.eclipse.keyple.plugin.remotese.rm.AbstractRemoteMethodTx$1.run(AbstractRemoteMethodTx.java:127)
```

**Comment by odelcroi** [comment]
https://keyple.atlassian.net/browse/KEYP-302
