### ISSUE TITLE
plugin : thread throws ConcurrentModificationException

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#274]
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1232)
       at java.util.TreeMap$KeyIterator.next(TreeMap.java:1286)
       at java.util.AbstractCollection.containsAll(AbstractCollection.java:315)
       at java.util.concurrent.ConcurrentSkipListSet.equals(ConcurrentSkipListSet.java:283)
       at org.eclipse.keyple.core.seproxy.plugin.AbstractThreadedObservablePlugin$EventThread.run(AbstractThreadedObservablePlugin.java:178)

**Comment by odelcroi** [comment]
This exception can be raised if the result returned by the method  AbstractThreadedObservablePlugin#fetchNativeReadersNames() is modified in a concurrent way. This is the responsibility of plugin developer to handle this. Though the documentation of the plugin API should be more explicit on this issue
