### ISSUE TITLE
ConcurentModification Exception thrown when  attempt to remove virtualReader

### ISSUE THREAD

**Issue by hicham-elbizy** [eclipse/keyple-java#304]
the concurrent modification detected  in environnement multithreading : 

	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265)
	at org.eclipse.keyple.plugin.remotese.pluginse.RemoteSePluginImpl.getReaderByRemoteName(RemoteSePluginImpl.java:67)
	at org.eclipse.keyple.plugin.remotese.pluginse.RemoteSePluginImpl.removeVirtualReader(RemoteSePluginImpl.java:146)

**Comment by odelcroi** [comment]
https://keyple.atlassian.net/browse/KEYP-203
